steps:
  - name: publish
    image: plugins/kaniko
    settings:
      registry:
        from_secret: docker_registry
      repo:
        from_secret: docker_repo
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
